slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    ignore_scan_errors: true # We are ignoring scans since our lidar is 668 (We must fix later for now just ignore)
    scan_queue_size: 10 # reduced from 100 to limit backlog

    enable_interactive_mode: true
    publish_pose_graph: true
    max_iterations: 1000
    max_iterations_loop: 1000
    scan_buffer_size: 100

    publish_tf: true # test add
    odom_frame: odom
    map_frame: map
    base_frame: base_link  # originally base_footprint, under the impression that it match robot_localization's base_frame
    scan_topic: /scan
    use_map_saver: true
    mode: mapping          #localization 

    publish_map: true
    queue_size: 1000
    use_sim_time: false

    use_scan_params_from_topic: true

    # if you'd like to immediately start continuing a map at a given pose
    # or at the dock, but they are mutually exclusive, if pose is given
    # will use pose
    #map_file_name: test_steve
    # map_start_pose: [0.0, 0.0, 0.0]
    #map_start_at_dock: true

    debug_logging: false
    throttle_scans: 1 # process every scan (was 2)
    transform_publish_period: 0.02 # if 0 never publishes odometry
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 8.0 #for rastering images #orginally 20.0
    minimum_time_interval: 0.5
    transform_timeout: 0.1 # lowered from 0.2 to reduce queueing
    tf_buffer_duration: 5.0 # lowered from 30.0 to avoid stale transforms
    stack_size_to_use: 40000000 # program needs a larger stack size to serialize large maps
    enable_interactive_mode: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    

    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
