name: ROS2 Jazzy CI (with Container)

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup ROS2 environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Update and Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            nlohmann-json3-dev \
            libgeographiclib-dev \
            libserial-dev \
            python3-vcstool \
            python3-colcon-common-extensions

      - name: Clone Navigation2 System Tests
        run: |
          cd FollowBotAROS2/src
          git clone --branch main https://github.com/ros-planning/navigation2.git
          vcs import < navigation2/tools/ros2-navigation2.repos
        shell: bash

      - name: Install ROS 2 Package Dependencies
        run: |
          source /opt/ros/jazzy/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
        working-directory: FollowBotAROS2
        shell: bash

      - name: Build Workspace (Project + Nav2 System Tests)
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --symlink-install
        working-directory: FollowBotAROS2
        shell: bash

      - name: Test Workspace (Project + Nav2 System Tests)
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon test --packages-select nav2_system_tests
          colcon test-result --verbose
        working-directory: FollowBotAROS2
        shell: bash

      - name: Upload Test Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: FollowBotAROS2/log
